const menuItems = [
  {
    id: 1,
    name: 'NVIDIA RTX 4090',
    category: 'GPU',
    price: 1599.99,
    image: 'https://i.pinimg.com/236x/15/58/cc/1558cc2db9a80b8b5de8b7f7eb5396df.jpg',
    rating: 4.9,
    description:
      'Flagship graphics card with 24GB GDDR6X memory. Ultimate performance for 4K gaming, ray tracing, and content creation. Features Ada Lovelace architecture with 16,384 CUDA cores.',
    isPopular: true,
    isOffers: true,
    offer: '20%',
    tax: 4.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 2,
    name: 'AMD Ryzen 9 7950X',
    category: 'CPU',
    price: 699.99,
    image: 'https://i.pinimg.com/236x/3b/f1/47/3bf1474f08e94c0741060a0f1f947391.jpg',
    rating: 4.8,
    description:
      '16-core, 32-thread processor with 5.7GHz boost clock. Exceptional multi-threaded performance for gaming, streaming, and professional workloads with Zen 4 architecture.',
    isPopular: true,
    isOffers: true,
    offer: '20%',
    tax: 4.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 3,
    name: 'Corsair Vengeance DDR5',
    category: 'RAM',
    price: 189.99,
    image: 'https://m.media-amazon.com/images/I/61EVf-QxpvL.jpg',
    rating: 4.7,
    description: '32GB (2x16GB) DDR5-6000 RAM kit with optimized latency. Built for high-performance gaming and content creation with RGB lighting and aluminum heatspreaders.',
    isPopular: false,
    isOffers: true,
    offer: '20%',
    tax: 4.5,
    isVip: false,
    warranty: 'Lifetime',
  },
  {
    id: 4,
    name: 'Samsung 990 PRO SSD',
    category: 'Storage',
    price: 199.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%2Fid%2FOIP.SjKK7DGgnRnBZVcs-VKJlQHaJ1%3Fcb%3Ducfimg2%26pid%3DApi%26ucfimg%3D1&f=1&ipt=f9f1a480694e17c32a05a7feffd92a01af7bb06971ae566b02490743d9af22aa&ipo=images',
    rating: 4.9,
    description: "2TB NVMe M.2 SSD with PCIe 4.0 interface. Lightning-fast read speeds up to 7,450 MB/s with Samsung's latest V-NAND technology. Perfect for OS and games.",
    isPopular: true,
    isOffers: true,
    offer: '20%',
    tax: 4.5,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 5,
    name: 'NVIDIA RTX 4070 Ti',
    category: 'GPU',
    price: 799.99,
    image: 'https://i.pinimg.com/236x/35/58/d2/3558d2099dc097a87408f4f6cbc7b6fa.jpg',
    rating: 4.8,
    description: 'Powerful mid-range graphics card with 12GB GDDR6X. Excellent 1440p and 4K gaming performance with DLSS 3.0 support and efficient power consumption.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 4.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 6,
    name: 'Intel Core i9-14900K',
    category: 'CPU',
    price: 589.99,
    image: 'https://i.pinimg.com/236x/35/ed/d9/35edd9039a5b18fb60e84e7b2085482c.jpg',
    rating: 4.8,
    description: '24-core (8P+16E) processor with 6.0GHz turbo frequency. Superior gaming performance and multi-tasking with Intel Thread Director and Raptor Lake architecture.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 4.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 7,
    name: 'G.Skill Trident Z5 RGB',
    category: 'RAM',
    price: 249.99,
    image: 'https://i.pinimg.com/236x/de/13/64/de13642a07329a7b7b6eb4df20cf6ac7.jpg',
    rating: 4.7,
    description: '32GB (2x16GB) DDR5-6400 high-performance memory. Premium RGB lighting with customizable effects. Optimized for Intel and AMD platforms.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 4.5,
    isVip: false,
    warranty: 'Lifetime',
  },
  {
    id: 8,
    name: 'WD Black SN850X',
    category: 'Storage',
    price: 249.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.extreme-pc.ca%2Fmedia%2Fwysiwyg%2Fexternal%2F81eghpj1i5l._ac_sl1500_.jpg.jpeg&f=1&nofb=1&ipt=08bc061a774bbacc84dab49bb70f444bb1d5ecd54c9d58a6fe5bdc4cf8e5afbf',
    rating: 4.8,
    description: '2TB Gen4 NVMe SSD with up to 7,300 MB/s read speeds. Game Mode 2.0 technology for predictable high-speed performance. Built-in heatsink included.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 4.5,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 9,
    name: 'AMD Radeon RX 7900 XTX',
    category: 'GPU',
    price: 999.99,
    image: 'https://i.pinimg.com/736x/bf/a1/a2/bfa1a2ddd1d059b12f3b9547a69abeeb.jpg',
    rating: 4.7,
    description: '24GB GDDR6 flagship AMD graphics card. Exceptional 4K gaming performance with RDNA 3 architecture, AMD FidelityFX and hardware-accelerated ray tracing.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 4.0,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 10,
    name: 'AMD Ryzen 7 7800X3D',
    category: 'CPU',
    price: 449.99,
    image: 'https://i.pinimg.com/736x/b7/ba/7e/b7ba7e82aa1741293e725b6fe92df46d.jpg',
    rating: 4.9,
    description: '8-core gaming champion with 3D V-Cache technology. Best-in-class gaming performance with 96MB cache and efficient 120W TDP. The ultimate gaming processor.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 4.0,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 11,
    name: 'Kingston Fury Beast DDR4',
    category: 'RAM',
    price: 129.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.cybertrade.bg%2Fimage%2Fcatalog%2Fkingston%2Ffury-beast-ddr4%2Fkingston-fury-beast-ddr4-13.jpg&f=1&nofb=1&ipt=1f9070530ebbfb7f106499a3ede3011976b163208c3af5c4433c8a2d03608673',
    rating: 4.6,
    description: '32GB (2x16GB) DDR4-3600 CL16 memory kit. Reliable performance with aggressive heatspreader design. Plug-and-play compatibility with Intel XMP.',
    isPopular: false,
    isOffers: true,
    offer: '14%',
    tax: 2.5,
    isVip: false,
    warranty: 'Lifetime',
  },
  {
    id: 12,
    name: 'Crucial P5 Plus',
    category: 'Storage',
    price: 159.99,
    image: 'https://i.pinimg.com/236x/28/d7/9f/28d79f0ec7758bc5cd094ba71859e170.jpg',
    rating: 4.7,
    description: '2TB PCIe 4.0 NVMe M.2 SSD with read speeds up to 6,600 MB/s. Ideal for gaming and professional workloads with Micron advanced 3D NAND technology.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 6.5,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 13,
    name: 'NVIDIA RTX 4060 Ti',
    category: 'GPU',
    price: 399.99,
    image: 'https://i.pinimg.com/236x/fd/83/a7/fd83a7941671aefafff6460b3bd26382.jpg',
    rating: 4.6,
    description: '8GB GDDR6 mainstream gaming GPU. Excellent 1080p and 1440p performance with DLSS 3.0, ray tracing, and low power consumption. Perfect for budget builds.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 9.0,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 14,
    name: 'Intel Core i5-14600K',
    category: 'CPU',
    price: 319.99,
    image: 'https://i.pinimg.com/236x/24/49/35/24493555e6615ad1c7afb4fa5a10d5f3.jpg',
    rating: 4.7,
    description: '14-core (6P+8E) processor with 5.3GHz turbo. Exceptional value for gaming and productivity with unlocked multiplier for overclocking.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 4.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 15,
    name: 'Seagate FireCuda 530',
    category: 'Storage',
    price: 279.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flagihitech.vn%2Fwp-content%2Fuploads%2F2022%2F02%2FSSD-Seagate-Firecuda-530-1TB-M.2-PCIe-Gen4x4-NVMe-ZP1000GM30013-hinh-2.jpg&f=1&nofb=1&ipt=e42343d41f0a1667f29dd3a5715cb4e0aed0ddaeec0c06fcce91ce9f3666f072',
    rating: 4.8,
    description: '2TB PCIe Gen4 NVMe SSD with heatsink. Professional-grade performance up to 7,300 MB/s with 5-year warranty and data recovery services.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 7.5,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 16,
    name: 'Corsair Dominator DDR5',
    category: 'RAM',
    price: 349.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.pangoly.com%2Fimg%2Fc%2Fc%2F4%2Fb%2Fcc4b4a51-170f-4c99-9715-21b3d54a19bf.jpg&f=1&nofb=1&ipt=a503848a1b1180c8ef6c5a512e02df609760bd06bd4e1cfe81bcb313df38d145',
    rating: 4.9,
    description: '32GB (2x16GB) DDR5-6600 premium memory. Hand-sorted ICs, patented DHX cooling, and customizable RGB. Built for extreme overclocking performance.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 7.5,
    isVip: false,
    warranty: 'Lifetime',
  },
  {
    id: 17,
    name: 'AMD Ryzen 5 7600X',
    category: 'CPU',
    price: 299.99,
    image: 'https://mesajil.com/wp-content/uploads/2022/11/31823.webp',
    rating: 4.6,
    description: '6-core, 12-thread Zen 4 processor. Great value for gaming with 5.3GHz boost and efficient 105W TDP. Perfect for budget gaming builds.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 7.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 18,
    name: 'Samsung 870 EVO SATA',
    category: 'Storage',
    price: 119.99,
    image: 'https://levendonline.com/cdn/shop/files/Samsung870evo1Tb.png?v=1731602320',
    rating: 4.7,
    description: '1TB 2.5-inch SATA SSD with 560 MB/s read speeds. Reliable storage solution for secondary drives, mass storage, and laptop upgrades.',
    isPopular: false,
    isOffers: true,
    offer: '7%',
    tax: 7.0,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 19,
    name: 'ASUS ROG Strix RTX 4080',
    category: 'GPU',
    price: 1099.99,
    image: 'https://www.creatus.com.bd/image/cache/catalog/2022/03/asus-strix-RTX30801-500x500-1-500x500.jpg.webp',
    rating: 4.8,
    description: '16GB GDDR6X high-end GPU with advanced cooling. Premium performance for 4K gaming with Axial-tech fans and MaxContact technology for superior heat dissipation.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 2.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 20,
    name: 'Intel Core i7-14700K',
    category: 'CPU',
    price: 409.99,
    image: 'https://i.pinimg.com/736x/0d/9d/e8/0d9de8f7f1cd31b8a53df14bd918a8e2.jpg',
    rating: 4.8,
    description: '20-core (8P+12E) processor with 5.6GHz turbo. Excellent balance of gaming and productivity performance with Raptor Lake architecture.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 9.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 21,
    name: 'Crucial Ballistix DDR4',
    category: 'RAM',
    price: 109.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flatestintech.com%2Fwp-content%2Fuploads%2F2020%2F12%2Fcrucial-ballistix-max-review.jpg&f=1&nofb=1&ipt=4818d0a816016bf6aa5185028440080720bb98654fe348e60eeb8665e2ee61bf',
    rating: 4.5,
    description: '32GB (2x16GB) DDR4-3200 CL16 memory. Great value for mainstream gaming builds with solid performance and Micron-quality memory chips.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: 'Lifetime',
  },
  {
    id: 22,
    name: 'Sabrent Rocket 4 Plus',
    category: 'Storage',
    price: 189.99,
    image: 'https://sabrent.com/cdn/shop/products/Square4_d55922b7-4fa7-4dee-8354-2e49031690e9_2048x.jpg?v=1688176245',
    rating: 4.7,
    description: '2TB PCIe 4.0 M.2 SSD with blazing read speeds up to 7,000 MB/s. Includes aluminum heatsink for optimal thermal management during intense workloads.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 23,
    name: 'MSI Gaming GeForce RTX 4070',
    category: 'GPU',
    price: 599.99,
    image: 'https://i.pinimg.com/236x/f1/7d/db/f17ddbd0bf3b2372b600686be9ce1889.jpg',
    rating: 4.7,
    description: '12GB GDDR6X graphics card with Twin Frozr 9 cooling. Excellent 1440p gaming performance with DLSS 3.0, ray tracing, and efficient Ada Lovelace architecture.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 24,
    name: 'AMD Ryzen 9 7900X',
    category: 'CPU',
    price: 549.99,
    image: 'https://i.pinimg.com/236x/17/7a/8b/177a8b44c8c49809a464836436e0432f.jpg',
    rating: 4.7,
    description: '12-core, 24-thread Zen 4 processor with 5.4GHz boost. High performance for content creation and gaming with 64MB L3 cache and AM5 platform.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 25,
    name: 'TeamGroup T-Force Delta RGB',
    category: 'RAM',
    price: 159.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fnetcodex.ph%2Fwp-content%2Fuploads%2F2023%2F02%2F9e2e0cefdc783e09d1eb88f3f5e9c9aa.jpg&f=1&nofb=1&ipt=3f0afff979373d695109dc410b696b9c85cf1073f83dee11210ebd2522e695b2',
    rating: 4.6,
    description: '32GB (2x16GB) DDR5-5600 with full-length RGB lighting. Force Flow RGB design with 120° ultra-wide lighting angle for stunning visuals.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: 'Lifetime',
  },
  {
    id: 26,
    name: 'Kingston NV2 NVMe',
    category: 'Storage',
    price: 89.99,
    image: 'https://c1.neweggimages.com/productimage/nb640/20-242-729-07.jpg',
    rating: 4.5,
    description: '1TB PCIe 4.0 NVMe M.2 SSD with read speeds up to 3,500 MB/s. Budget-friendly storage solution perfect for everyday computing and light gaming.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 9.0,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 27,
    name: 'Gigabyte Radeon RX 7800 XT',
    category: 'GPU',
    price: 499.99,
    image: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/7f7990e5-0ae2-4e1c-b01d-90c35b30da47.__CR0,0,970,600_PT0_SX970_V1___.jpg',
    rating: 4.6,
    description: '16GB GDDR6 GPU with Windforce cooling. Excellent 1440p gaming performance with RDNA 3 architecture, FSR 3.0, and hardware ray tracing support.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.0,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 28,
    name: 'Intel Core i3-14100F',
    category: 'CPU',
    price: 119.99,
    image: 'https://digitalsmart.ec/wp-content/uploads/2024/01/PROCESADOR-INTEL-CORE-I3-14100F-GEN-14-LGA1700-4-NUCLEOS-8-HILOS-2.jpg',
    rating: 4.4,
    description: '4-core, 8-thread budget processor with 4.7GHz turbo. Great entry-level CPU for gaming builds. No integrated graphics (requires discrete GPU).',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.0,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 29,
    name: 'Patriot Viper Steel DDR4',
    category: 'RAM',
    price: 94.99,
    image: 'https://sipoonline.cl/wp-content/uploads/2024/07/Gabinete-Crystal-Black-RGB-EATX-Vidrio-Templado-USB-3.0-3_5.png',
    rating: 4.5,
    description: '32GB (2x16GB) DDR4-3200 CL16 memory with aluminum heatspreader. Reliable performance for budget builds with XMP 2.0 support.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.0,
    isVip: false,
    warranty: 'Lifetime',
  },
  {
    id: 30,
    name: 'Corsair MP600 PRO XT',
    category: 'Storage',
    price: 229.99,
    image: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/fd122122-f77c-481b-8d33-da9a514932ad.__CR0,0,800,600_PT0_SX600_V1___.jpg',
    rating: 4.7,
    description: '2TB Gen4 PCIe x4 NVMe SSD with aluminum heatspreader. High-density 3D TLC NAND for exceptional endurance with speeds up to 7,100 MB/s.',
    isPopular: false,
    isOffers: true,
    offer: '30%',
    tax: 1.0,
    isVip: false,
    warranty: '5 Years',
  },
  // RTX 3000 Series
  {
    id: 31,
    name: 'ASUS ROG Strix GeForce RTX 3090',
    category: 'GPU',
    price: 1499.99,
    image: 'https://static.tweaktown.com/content/1/0/10075_511_asus-rog-strix-lc-geforce-rtx-3090-ti-oc-edition-review_full.jpg',
    rating: 4.8,
    description: '24GB GDDR6X flagship GPU for 4K and 8K gaming, heavy rendering, and AI workloads. Exceptional ray tracing and DLSS performance.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 32,
    name: 'Gigabyte GeForce RTX 3080 Gaming OC',
    category: 'GPU',
    price: 799.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD2VYIGa4IobnheGtjAYSmCwJVRLCZBSLpWA&s',
    rating: 4.7,
    description: '10GB GDDR6X GPU optimized for 4K gaming with WINDFORCE cooling, ray tracing, and DLSS support.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 33,
    name: 'MSI GeForce RTX 3070 Ventus 2X',
    category: 'GPU',
    price: 499.99,
    image: 'https://www.megabytes.cl/wp-content/uploads/2023/10/0cc9dca3-e9b1-4c6e-9fa9-048fa537173a.jpg',
    rating: 4.6,
    description: '8GB GDDR6 graphics card ideal for 1440p gaming with solid ray tracing and DLSS performance.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },

  // RTX 5000 Series (futura / placeholder)
  {
    id: 34,
    name: 'NVIDIA GeForce RTX 5090',
    category: 'GPU',
    price: 1999.99,
    image: 'https://www.fabritec.pe/assets/media/producto/734-RTX-3060-8GB-TWIN-EDGE-3.jpg',
    rating: 5.0,
    description: 'Next-generation flagship GPU with massive AI performance, advanced ray tracing, and DLSS 4.0. Designed for 4K+ ultra gaming and creators.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 35,
    name: 'NVIDIA GeForce RTX 5080',
    category: 'GPU',
    price: 1299.99,
    image:
      'https://external-preview.redd.it/nvidia-geforce-rtx-5080-16-gb-gpu-first-to-launch-in-v0-fsbAKKqrlwkWCeFMGRAyPh0yWDAiraY0h1N8pZeAUPI.jpg?width=1080&crop=smart&auto=webp&s=1bd9e6501c98b6b0f0fc72515d81072987c66efe',
    rating: 4.9,
    description: 'High-end next-gen GPU focused on 4K gaming, improved efficiency, and enhanced ray tracing cores.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 36,
    name: 'NZXT Kraken X73 RGB',
    category: 'Cooling',
    price: 219.99,
    image: 'https://supremeitmall.com/wp-content/uploads/2021/12/71A2T82qE4L._AC_SL1500_.jpg',
    rating: 4.8,
    description: '360mm AIO liquid CPU cooler with RGB lighting, powerful Aer P fans, and excellent thermal performance for high-end processors.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '2 Years',
  },
  // PC Cooling
  {
    id: 37,
    name: 'Corsair iCUE H150i Elite Capellix',
    category: 'Cooling',
    price: 249.99,
    image:
      'https://assets.corsair.com/image/upload/c_pad,q_auto,h_1024,w_1024,f_auto/products/Custom-Cooling/CW-9060070-WW/-base-elite-capellix-xt-cooler-config-Gallery-H150i-ELITE-CAPELLIX-XT-03.webp',
    rating: 4.9,
    description: 'Premium 360mm liquid CPU cooler with Capellix RGB LEDs, high-performance ML fans, and iCUE software control.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '2 Years',
  },
  {
    id: 38,
    name: 'Noctua NH-D15 chromax.black',
    category: 'Cooling',
    price: 109.99,
    image: 'https://i.pinimg.com/736x/5f/f8/81/5ff8813dcf8123093e62fec987b86b85.jpg',
    rating: 4.9,
    description: 'High-end dual-tower air cooler with exceptional cooling performance, ultra-quiet operation, and premium build quality.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '2 Years',
  },
  {
    id: 39,
    name: 'Cooler Master Hyper 212 Black Edition',
    category: 'Cooling',
    price: 44.99,
    image: 'https://i.ytimg.com/vi/TSbW-UcLS-g/maxresdefault.jpg',
    rating: 4.6,
    description: 'Popular air CPU cooler featuring a 120mm fan, direct-contact heat pipes, and excellent value for mainstream builds.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '1 Year',
  },
  {
    id: 40,
    name: 'Lian Li UNI Fan SL120 V2 (3-Pack)',
    category: 'Cooling',
    price: 99.99,
    image: 'https://i.ytimg.com/vi/5cnUi7lLb0Q/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCUh7N_bouIpIoGA1CVLHzoDIfdTg',
    rating: 4.7,
    description: '120mm RGB case fans with modular interlocking design, excellent airflow, and clean cable management.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '2 Years',
  },
  {
    id: 41,
    name: 'Arctic P12 PWM PST (5-Pack)',
    category: 'Cooling',
    price: 39.99,
    image: 'https://m.media-amazon.com/images/I/61Gi-z6yBcL._AC_UF350,350_QL80_.jpg',
    rating: 4.8,
    description: 'High-efficiency 120mm PWM fans optimized for static pressure, ideal for radiators and case airflow.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '1 Year',
  },
  {
    id: 42,
    name: 'NZXT Kraken Z73',
    category: 'Cooling',
    price: 279.99,
    image: 'https://hexus.net/media/uploaded/2020/2/c54bd971-a485-4513-8c24-ded9f6dc8b84.png',
    rating: 4.9,
    description: '360mm AIO liquid CPU cooler with customizable LCD display, RGB fans, and top-tier thermal performance for enthusiast builds.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '2 Years',
  },
  {
    id: 43,
    name: 'Corsair iCUE H100i Elite LCD',
    category: 'Cooling',
    price: 189.99,
    image: 'https://i5.walmartimages.com/asr/6aca7015-b6ef-49a3-91d0-2ac6dce5d694.3759bb6f11673a4138d51f3c7a7c29fc.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
    rating: 4.8,
    description: '240mm AIO liquid cooler with LCD screen, high static-pressure fans, and advanced iCUE RGB and performance control.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '2 Years',
  },
  {
    id: 44,
    name: 'Lian Li Galahad II Trinity 360',
    category: 'Cooling',
    price: 239.99,
    image: 'https://i.ytimg.com/vi/OyZEZv3F8K0/maxresdefault.jpg',
    rating: 4.7,
    description: '360mm AIO liquid CPU cooler with interchangeable pump caps, powerful RGB fans, and sleek minimalist design.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '2 Years',
  },
  {
    id: 45,
    name: 'Arctic Liquid Freezer II 360',
    category: 'Cooling',
    price: 139.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiAh-yy8pVS_TO1Tn5D7hPN1vmqtiNsmWa7g&s',
    rating: 4.9,
    description: 'High-performance 360mm AIO liquid cooler featuring an additional VRM fan and excellent price-to-performance ratio.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '2 Years',
  },
  {
    id: 46,
    name: 'DeepCool LS520 SE',
    category: 'Cooling',
    price: 109.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD_qldobC6Z6QrkBrt8jI72gCntyjssP0BQw&s',
    rating: 4.6,
    description: '240mm AIO liquid CPU cooler with ARGB pump head, quiet operation, and solid cooling performance for mid-range systems.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '1 Year',
  },
  {
    id: 47,
    name: 'NVIDIA GeForce RTX 5070',
    category: 'GPU',
    price: 799.99,
    image: 'https://elchapuzasinformatico.com/wp-content/uploads/2024/12/NVIDIA-GeForce-RTX-5070-especificaciones-12-GB-memoria-VRAM-GDDR7.jpg',
    rating: 4.8,
    description: 'Mid-high range GPU delivering excellent 1440p and entry-level 4K gaming with next-gen DLSS and ray tracing.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 48,
    name: 'ZOTAC Gaming GeForce RTX 3060 Twin Edge',
    category: 'GPU',
    price: 329.99,
    image: 'https://www.pcguide.com/wp-content/uploads/2023/06/Zotac-3060Ti-Amazon-deal.jpg',
    rating: 4.5,
    description: '12GB GDDR6 GPU designed for 1080p and 1440p gaming with ray tracing and DLSS.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 49,
    name: 'ASUS ROG Strix Z790-E Gaming, WiFi',
    category: 'Motherboard',
    price: 429.99,
    image: 'https://i.pinimg.com/736x/64/08/08/640808ca58c1d1759820aa2339d5ae4b.jpg',
    rating: 4.8,
    description: 'Intel Z790 ATX motherboard with PCIe 5.0, DDR5 support, WiFi 6E, and premium power delivery for high-end gaming builds.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 50,
    name: 'MSI MAG B650 Tomahawk WiFi',
    category: 'Motherboard',
    price: 219.99,
    image: 'https://i.pinimg.com/736x/02/b4/a8/02b4a868724a0e422f3bd10539d4c2dc.jpg',
    rating: 4.7,
    description: 'AMD B650 ATX motherboard supporting Ryzen 7000 series, DDR5 memory, PCIe 4.0, and integrated WiFi 6E.',
    isPopular: true,
    isOffers: true,
    offer: '10%',
    tax: 3.5,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 51,
    name: 'Gigabyte X670 AORUS Elite AX',
    category: 'Motherboard',
    price: 299.99,
    image: 'https://i.pinimg.com/736x/f0/fe/48/f0fe487fcd506f651080bee7108173c4.jpg',
    rating: 4.6,
    description: 'High-performance AMD X670 motherboard with PCIe 5.0 support, DDR5, advanced cooling, and AORUS power design.',
    isPopular: true,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '5 Years',
  },
  {
    id: 52,
    name: 'ASRock B550M Steel Legend',
    category: 'Motherboard',
    price: 159.99,
    image: 'https://i.pinimg.com/736x/aa/89/96/aa8996fedf06af80463fcb66c80cfb6c.jpg',
    rating: 4.5,
    description: 'Micro-ATX B550 motherboard for AMD Ryzen processors with PCIe 4.0, reinforced steel slots, and solid VRM cooling.',
    isPopular: false,
    isOffers: true,
    offer: '30%',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 53,
    name: 'ASUS Prime H610M-E D4',
    category: 'Motherboard',
    price: 99.99,
    image: 'https://i.pinimg.com/736x/23/03/c5/2303c5cf1b7ee50e9e98e718a59ff25d.jpg',
    rating: 4.3,
    description: 'Entry-level Intel H610 micro-ATX motherboard with DDR4 support, ideal for office and budget PC builds.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 3.5,
    isVip: false,
    warranty: '3 Years',
  },
  {
    id: 54,
    name: 'Intel Arc A750',
    category: 'GPU',
    price: 249.99,
    image: 'https://i.pinimg.com/736x/47/6e/f1/476ef1dcebdf13e861c06a978f3581ca.jpg',
    rating: 4.0,
    description: 'Intel Arc GPU with 8GB GDDR6, XeSS upscaling, and AV1 encoding support.',
    isPopular: false,
    isOffers: false,
    offer: '',
    tax: 10.5,
    isVip: false,
    warranty: '3 Years',
  },
];
