export const menuItems = [
  {
    id: '01-vip',
    name: 'NVIDIA RTX 4090',
    category: 'GPU',
    price: 1599.99,
    image: 'https://i.pinimg.com/236x/15/58/cc/1558cc2db9a80b8b5de8b7f7eb5396df.jpg',
    rating: 4.9,
    description:
      'Flagship graphics card with 24GB GDDR6X memory. Ultimate performance for 4K gaming, ray tracing, and content creation. Features Ada Lovelace architecture with 16,384 CUDA cores.',
    isPopular: true,
    isOffers: true,
    offer: '42%',
    tax: 3.5,
    isVip: true,
    warranty: '2 Years',
  },
  {
    id: '02-vip',
    name: 'AMD Ryzen 9 7950X',
    category: 'CPU',
    price: 699.99,
    image: 'https://i.pinimg.com/236x/3b/f1/47/3bf1474f08e94c0741060a0f1f947391.jpg',
    rating: 4.8,
    description:
      '16-core, 32-thread processor with 5.7GHz boost clock. Exceptional multi-threaded performance for gaming, streaming, and professional workloads with Zen 4 architecture.',
    isPopular: true,
    isOffers: true,
    offer: '35%',
    tax: 4.5,
    isVip: true,
    warranty: '3 Years',
  },
  {
    id: '03-vip',
    name: 'Corsair Vengeance DDR5',
    category: 'RAM',
    price: 189.99,
    image: 'https://m.media-amazon.com/images/I/61EVf-QxpvL.jpg',
    rating: 4.7,
    description: '32GB (2x16GB) DDR5-6000 RAM kit with optimized latency. Built for high-performance gaming and content creation with RGB lighting and aluminum heatspreaders.',
    isPopular: false,
    isOffers: true,
    offer: '30%',
    tax: 4.5,
    isVip: true,
    warranty: '3 Years',
  },
  {
    id: '04-vip',
    name: 'Samsung 990 PRO SSD',
    category: 'Storage',
    price: 199.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%2Fid%2FOIP.SjKK7DGgnRnBZVcs-VKJlQHaJ1%3Fcb%3Ducfimg2%26pid%3DApi%26ucfimg%3D1&f=1&ipt=f9f1a480694e17c32a05a7feffd92a01af7bb06971ae566b02490743d9af22aa&ipo=images',
    rating: 4.9,
    description: "2TB NVMe M.2 SSD with PCIe 4.0 interface. Lightning-fast read speeds up to 7,450 MB/s with Samsung's latest V-NAND technology. Perfect for OS and games.",
    isPopular: true,
    isOffers: true,
    offer: '25%',
    tax: 4.5,
    isVip: true,
    warranty: '5 Years',
  },
  {
    id: '05-vip',
    name: 'NVIDIA RTX 5090',
    category: 'GPU',
    price: 1999.99,
    image: 'https://www.fabritec.pe/assets/media/producto/734-RTX-3060-8GB-TWIN-EDGE-3.jpg',
    rating: 5.0,
    description: 'Next-generation flagship GPU with massive AI performance, advanced ray tracing, and DLSS 4.0. Designed for 4K+ ultra gaming and creators.',
    isPopular: true,
    isOffers: true,
    offer: '50%',
    tax: 3.5,
    isVip: true,
    warranty: '2 Years',
  },
  {
    id: '06-vip',
    name: 'NVIDIA RTX 5080',
    category: 'GPU',
    price: 1299.99,
    image:
      'https://external-preview.redd.it/nvidia-geforce-rtx-5080-16-gb-gpu-first-to-launch-in-v0-fsbAKKqrlwkWCeFMGRAyPh0yWDAiraY0h1N8pZeAUPI.jpg?width=1080&crop=smart&auto=webp&s=1bd9e6501c98b6b0f0fc72515d81072987c66efe',
    rating: 4.9,
    description: 'High-end next-gen GPU focused on 4K gaming, improved efficiency, and enhanced ray tracing cores.',
    isPopular: true,
    isOffers: true,
    offer: '45%',
    tax: 4.1,
    isVip: true,
    warranty: '2 Years',
  },
  {
    id: '07-vip',
    name: 'Intel Core i9-14900K',
    category: 'CPU',
    price: 589.99,
    image: 'https://i.pinimg.com/236x/35/ed/d9/35edd9039a5b18fb60e84e7b2085482c.jpg',
    rating: 4.8,
    description: '24-core (8P+16E) processor with 6.0GHz turbo frequency. Superior gaming performance and multi-tasking with Intel Thread Director and Raptor Lake architecture.',
    isPopular: false,
    isOffers: true,
    offer: '32%',
    tax: 4.5,
    isVip: true,
    warranty: '3 Years',
  },
  {
    id: '08-vip',
    name: 'Corsair MP600 PRO XT',
    category: 'Storage',
    price: 229.99,
    image: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/fd122122-f77c-481b-8d33-da9a514932ad.__CR0,0,800,600_PT0_SX600_V1___.jpg',
    rating: 4.7,
    description: '2TB Gen4 PCIe x4 NVMe SSD with aluminum heatspreader. High-density 3D TLC NAND for exceptional endurance with speeds up to 7,100 MB/s.',
    isPopular: false,
    isOffers: true,
    offer: '60%',
    tax: 1.9,
    isVip: true,
    warranty: '5 Years',
  },
  {
    id: '09-vip',
    name: 'ASUS ROG Strix RTX 4080',
    category: 'GPU',
    price: 1099.99,
    image: 'https://www.creatus.com.bd/image/cache/catalog/2022/03/asus-strix-RTX30801-500x500-1-500x500.jpg.webp',
    rating: 4.8,
    description: '16GB GDDR6X high-end GPU with advanced cooling. Premium performance for 4K gaming with Axial-tech fans and MaxContact technology for superior heat dissipation.',
    isPopular: true,
    isOffers: true,
    offer: '38%',
    tax: 2.5,
    isVip: true,
    warranty: '2 Years',
  },
  {
    id: '10-vip',
    name: 'Corsair Dominator DDR5',
    category: 'RAM',
    price: 349.99,
    image:
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.pangoly.com%2Fimg%2Fc%2Fc%2F4%2Fb%2Fcc4b4a51-170f-4c99-9715-21b3d54a19bf.jpg&f=1&nofb=1&ipt=a503848a1b1180c8ef6c5a512e02df609760bd06bd4e1cfe81bcb313df38d145',
    rating: 4.9,
    description: '32GB (2x16GB) DDR5-6600 premium memory. Hand-sorted ICs, patented DHX cooling, and customizable RGB. Built for extreme overclocking performance.',
    isPopular: false,
    isOffers: true,
    offer: '42%',
    tax: 7.5,
    isVip: true,
    warranty: '3 Years',
  },
  {
    id: '11-vip',
    name: 'ASUS ROG Strix Z790-E Gaming, WiFi',
    category: 'Motherboard',
    price: 429.99,
    image: 'https://i.pinimg.com/736x/64/08/08/640808ca58c1d1759820aa2339d5ae4b.jpg',
    rating: 4.8,
    description: 'Intel Z790 ATX motherboard with PCIe 5.0, DDR5 support, WiFi 6E, and premium power delivery for high-end gaming builds.',
    isPopular: true,
    isOffers: true,
    offer: '50%',
    tax: 3.5,
    isVip: true,
    warranty: '1 Year',
  },
  {
    id: '12-vip',
    name: 'Gigabyte X670 AORUS Elite AX',
    category: 'Motherboard',
    price: 299.99,
    image: 'https://i.pinimg.com/736x/f0/fe/48/f0fe487fcd506f651080bee7108173c4.jpg',
    rating: 4.6,
    description: 'High-performance AMD X670 motherboard with PCIe 5.0 support, DDR5, advanced cooling, and AORUS power design.',
    isPopular: false,
    isOffers: true,
    offer: '60%',
    tax: 4.5,
    isVip: true,
    warranty: '1 Year',
  },
  {
    id: '13-vip',
    name: 'NVIDIA GeForce RTX 2060 Super',
    category: 'GPU',
    price: 289.99,
    image: 'https://i.pinimg.com/736x/1d/3d/21/1d3d21bda4e74adb46607c0b904a9a82.jpg',
    rating: 4.6,
    description: '8GB GDDR6 GPU delivering solid 1080p and entry-level 1440p gaming with ray tracing support.',
    isPopular: true,
    isOffers: true,
    offer: '70%',
    tax: 7.5,
    isVip: true,
    warranty: '2 Years',
  },
  {
    id: '14-vip',
    name: 'AMD Radeon RX 5700 XT',
    category: 'GPU',
    price: 279.99,
    image: 'https://www.asrock.com.tw/Graphics-Card/features/Die-Casting-Radeon%20RX%205700%20XT%208G_mobile.jpg',
    rating: 4.5,
    description: 'High-performance AMD GPU with 8GB GDDR6, ideal for high-refresh 1080p and 1440p gaming.',
    isPopular: false,
    isOffers: true,
    offer: '55%',
    tax: 3.5,
    isVip: true,
    warranty: '2 Years',
  },
  {
    id: '15-vip',
    name: 'Intel Arc A750',
    category: 'GPU',
    price: 249.99,
    image: 'https://i.pinimg.com/736x/47/6e/f1/476ef1dcebdf13e861c06a978f3581ca.jpg',
    rating: 4.3,
    description: 'Intel Arc GPU with 8GB GDDR6, XeSS upscaling, and AV1 encoding support.',
    isPopular: false,
    isOffers: true,
    offer: '81%',
    tax: 3.5,
    isVip: true,
    warranty: '2 Years',
  },
  {
    id: '16-vip',
    name: 'Intel Core i7-10700K',
    category: 'CPU',
    price: 239.99,
    image: 'https://m.media-amazon.com/images/I/71GnKVzz-uL._AC_SL1500_.jpg',
    rating: 4.7,
    description: '8-core Intel processor with strong gaming and multitasking performance.',
    isPopular: true,
    isOffers: true,
    offer: '22%',
    tax: 3.5,
    isVip: true,
    warranty: '3 Years',
  },
  {
    id: '17-vip',
    name: 'AMD Ryzen 7 3700X',
    category: 'CPU',
    price: 219.99,
    image: 'https://i.ebayimg.com/images/g/PNgAAOSwE~pmKgiC/s-l400.jpg',
    rating: 4.8,
    description: '8-core, 16-thread Ryzen CPU offering excellent productivity and gaming performance.',
    isPopular: true,
    isOffers: true,
    offer: '28%',
    tax: 4.9,
    isVip: true,
    warranty: '3 Years',
  },
  {
    id: '19-vip',
    name: 'G.Skill Trident Z RGB 32GB (2x16GB) DDR4 3600MHz',
    category: 'RAM',
    price: 129.99,
    image: 'https://www.gskill.com/_upload/images/156274347813.png',
    rating: 4.8,
    description: 'Premium RGB DDR4 memory with high speeds and excellent stability.',
    isPopular: false,
    isOffers: true,
    offer: '35%',
    tax: 2.2,
    isVip: true,
    warranty: '3 Years',
  },
  {
    id: '20-vip',
    name: 'MSI B550 Gaming Plus',
    category: 'Motherboard',
    price: 159.99,
    image: 'https://storage-asset.msi.com/global/picture/image/feature/mb/B550/MPG/gaming-plus/cooling-hero.jpg',
    rating: 4.6,
    description: 'ATX B550 motherboard with PCIe 4.0 support for AMD Ryzen processors.',
    isPopular: true,
    isOffers: true,
    offer: '30%',
    tax: 3.9,
    isVip: true,
    warranty: '1 Year',
  },
  {
    id: '21-vip',
    name: 'ASUS TUF Gaming Z490-Plus',
    category: 'Motherboard',
    price: 189.99,
    image: 'https://vision-techno.com/assets/images/columnsblocks/product270/48668.jpg',
    rating: 4.7,
    description: 'Durable Intel Z490 motherboard with enhanced power delivery and cooling.',
    isPopular: false,
    isOffers: true,
    offer: '26%',
    tax: 3.9,
    isVip: true,
    warranty: '1 Year',
  },
  {
    id: '22-vip',
    name: 'Samsung 970 EVO Plus 1TB NVMe SSD',
    category: 'Storage',
    price: 99.99,
    image: 'https://image.semiconductor.samsung.com/image/samsung/p6/semiconductor/consumer-storage/internal-ssd/970-evo-plus/970-evo-plus_pc_03.png?$ORIGIN_PNG$',
    rating: 4.9,
    description: 'High-speed NVMe SSD with excellent reliability and performance.',
    isPopular: true,
    isOffers: true,
    offer: '33%',
    tax: 7.5,
    isVip: true,
    warranty: '5 Years',
  },
  {
    id: '23-vip',
    name: 'WD Black SN750 500GB NVMe SSD',
    category: 'Storage',
    price: 69.99,
    image: 'https://www.system-max.com/wp-content/uploads/2023/04/81PXk_QyqFL._AC_SX679_bf15b494-a950-488e-8c9b-a31f41975775-600x600.jpg',
    rating: 4.7,
    description: 'Gaming-focused NVMe SSD with fast load times and stable performance.',
    isPopular: false,
    isOffers: true,
    offer: '29%',
    tax: 3.5,
    isVip: true,
    warranty: '5 Years',
  },
  {
    id: '24-vip',
    name: 'Cooler Master Hyper 212 Black Edition',
    category: 'Cooling',
    price: 44.99,
    image: 'https://www.vortez.net/articles_file/41247_cooler_master_hyper_212_black_edition_intro.jpg',
    rating: 4.6,
    description: 'Popular air cooler with silent operation and excellent thermal performance.',
    isPopular: true,
    isOffers: true,
    offer: '24%',
    tax: 2.5,
    isVip: true,
    warranty: '1 Year',
  },
  {
    id: '25-vip',
    name: 'NZXT Kraken X63 280mm AIO',
    category: 'Cooling',
    price: 139.99,
    image: 'https://product.hstatic.net/200000420363/product/fc_nzxt_kraken_x63-6_43c827ee8e9840f39ea52af27e141a23.jpg',
    rating: 4.8,
    description: 'Premium liquid cooler with RGB lighting and superior cooling efficiency.',
    isPopular: false,
    isOffers: true,
    offer: '36%',
    tax: 6.5,
    isVip: true,
    warranty: '2 Years',
  },
];
